dist: xenial
language: bash
addons:
  apt:
    packages:
    - curl
    - zip
    - unzip
before_script:
- sudo apt-get update -qq
- sudo apt-get install curl zip unzip check -qq
script:
- make
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: c3go1osy/T3T7qhZvQQnxR09ck5anmwGVQyQtrlx9B6QnQhLRF0NpV0CYt4PD6/4MUedCC0/EFmZpVogUyea/3F+F/j2fxsg4xUdm6gUNBKUH5wfdbHEW01JVfvwgtlZKFZmCrgNxS931yVM9yvPv02uPC4qjv2wP459wUbnEq5UkhOSaNd8rra1kaUnHdvqlJsBEKc7+lcElRuW5gFMknLXD2X3irXYr5+L2idVSmmApDwU9ufN5zAEUsh+4s3W7YZVxkrYuR2qZVHvA6jaFkKmdkO0giBaz9Tpz6UVErkWNtR6F3OWtjG3dj9dMOSIX4yjuugyDxhQsHZIbErg8TGYIIoW3tMydbgwmTOOCSKZoPSg07kByjiAQSlyVe9ISevUwyCU1TTcnQRF93/CMdDV7bnT8OAfFMkmTL/vqGNyijz5QhRVSswP8jfITx/L1jEXszEcB6hiTZu0y68tBy5ovW3o/V1Yhf03Ny941LG4AMkEuQytw5kALH8r/GKBy1HEbxSVvlaHb1ygwPh2AZoANXPGjvpBZ4gh3+95Tm0W2hMnPkbHtlXMQjfxVHabS96GB6l174aWxHD/u97bbL9AUUr2J2wx5LOoQf9Bf5mMRfPvHn8+JWgqLrO2D4LtOxNF2cGyip61uaMO36wyhbUyeFOMJEeGCNJv1wGVtK8=
  file_glob: true
  file: 'CentOS*.{zip}'
  on:
    repo: yuk7/CentWSL
    tags: true
    all_branches: true
  skip_cleanup: true
